### ISSUE TITLE
make_index.sh not working for cfg2html output versions 6.xx

### ISSUE THREAD

**Issue by vcbawane** [cfg2html/cfg2html#144]
**make_index.sh** not working for cfg2html output versions 6.xx, I think it has been updated for upto the version 5.xx but not for the latest versions

**Comment by roseswe** [comment]
I fixed make_index.sh for Linux HTML files, other OS also affected?

**Comment by vcbawane** [comment]
Hi Dear,

From where to get this new make_index.sh ?

Following are the details of the OS & cfg2html version for which I observed
make_index.sh is not working fine.

*Oracle Solaris 11.3 SPARC*

*cfg2html 6.37*

*HP-UX B.11.31 U ia64*

*cfg2html 6.27*

*HP-UX  B.11.23 U ia64*

*cfg2html 6.27*

*HP-UX  B.11.11*

*cfg2html 6.27*

*CentOS Linux release 7.8.2003 (Core)*

*cfg2html 6.41.1.0*



Thanks & Regards

Vinod

**Comment by vcbawane** [comment]
Hi Dear,

Still seems to be old file of make_index.sh at cfg2html.com, issue is
not solved, still skipping all html config files

Thanks & Regards
Vinod

**Comment by vcbawane** [comment]
Dear Team,
make_index.sh at cfg2html.com is working fine for linux & solaris hosts but
not for HP-UX host.

It is still skipping HP-UX hosts.

Thanks & Regards
Vinod

**Comment by roseswe** [comment]
Still open or OK to close?

**Comment by vcbawane** [comment]
pl. go ahead & close it

thanks & regards
Vinod
